apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

ext {
    bintrayRepo = 'maven'
    bintrayName = 'convertigo-sdk-android'

    publishedGroupId = 'com.convertigo.sdk'
    libraryName = 'c8oSDKAndroid'
    artifact = 'c8oSDKAndroid'

    libraryDescription = 'Allows Android apps to access Convertigo services such as FullSync data replication for offline, push notifications and back-end connectors'

    siteUrl = 'https://www.convertigo.com'
    gitUrl =  'https://github.com/convertigo/c8osdk-android'

    libraryVersion = '2.1.11'

    developerId = 'Convertigo'
    developerName = 'Convertigo SA'
    developerEmail = 'info@convertigo.com'

    licenseName = 'GNU General Public License'
    licenseUrl = 'https://www.gnu.org/licenses/gpl-3.0.en.html'
    allLicenses = ["GPL-3.0"]
}


android {
    namespace "com.convertigo.clientsdk"
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    defaultConfig {
        minSdkVersion 24
    }
    compileSdk = 33
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    productFlavors {
    }
    adbOptions {
        timeOutInMs 20 * 60 * 1000  // 20 minutes
        installOptions "-d","-t"
    }
    useLibrary 'org.apache.http.legacy'
}

dependencies {
    api 'com.couchbase.lite:couchbase-lite-android:1.4.1'
    api 'com.couchbase.lite:couchbase-lite-java-javascript:1.4.1'
}
afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = publishedGroupId
                artifactId = libraryName
                version = libraryVersion
            }
        }
        repositories {
            maven {
                url project.properties['c8o.m2.url']
                credentials(AwsCredentials) {
                    accessKey project.properties['c8o.m2.ak']
                    secretKey project.properties['c8o.m2.sk']
                }
            }
        }
    }
}